---
- name: Setup workstation
  hosts: localhost
  become: yes
  pre_tasks:
    - name: Update cache
      package:
        update_cache: true
      tags:
        - node
        - zsh

  tasks:
    - include_tasks: tasks/zsh.yml

    - name: Install fzf
      package:
        name: fzf
        state: present

    - name: Install gcc-c++
      package:
        name:
          - gcc-c++
        state: present

    - name: Install ripgrep
      package:
        name:
          - ripgrep
        state: present

    - name: Install go
      package:
        name: go
        state: present

    - name: Install htop
      package:
        name: go
        state: present

    - name: Install xclip
      package:
        name: xclip
        state: present

    - name: Install tldr
      package:
        name: tldr
        state: present

