---
- name: Setup workstation
  hosts: localhost
  become: yes
  pre_tasks:
    - name: Update cache
      package:
        update_cache: true
      tags:
        - zsh
        - nvim

  tasks:

    - name: Install git
      package:
        name: git
        state: present
      tags:
        - zsh
        - nvim

    - name: Install essential packages
      package:
        name:
          - xclip
          - unzip
          - curl
          - wget
          - gh
        state: present
      tags:
        - nvim
        - tmux
        - node

    - name: Install tmux
      package:
        name: tmux
        state: present
      tags: 
        - tmux

    # install fzf before zsh (prerequisite for zsh's history search)
    - name: Install fzf package
      package:
        name: fzf
        state: present
      tags:
        - nvim
        - scripts

    # zsh should be installed first so that other packages can add key bindings
    - include_tasks: tasks/zsh.yml
      tags: zsh

    # node should be installed after zsh and before nvim
    - include_tasks: tasks/node_setup.yml
      tags:
        - nvim
        - node

    - include_tasks: tasks/nvim.yml
      tags: nvim

    - include_tasks: tasks/stow.yml
      tags:
        - zshrc
        - tmux
        - gitconfig
        - stow

    - include_tasks: tasks/scripts.yml
      tags: scripts

    - include_tasks: tasks/optional_packages.yml
      tags: optional_packages

    # - include_tasks: tasks/flatpaks.yml
    #   tags: flatpaks

    # - include_tasks: tasks/clone.yml
    #   tags: clone
