---
- name: Setup workstation
  hosts: localhost
  become: yes
  pre_tasks:
    - name: Update cache
      package:
        update_cache: true
      tags:
        - zsh
        - nvim

  tasks:

    - name: Install git
      package:
        name: git
        state: present
      tags: 
        - zsh
        - nvim

    # fzf comes before zsh so that zsh can use fuzzy command history search
    - name: Install fzf
      package:
        name: fzf
        state: present
      tags: nvim

    # zsh should be installed first so that other packages can add key bindings
    - include_tasks: tasks/zsh.yml
      tags: zsh

    - include_tasks: tasks/nvim.yml
      tags: nvim

    - include_tasks: tasks/flatpaks.yml
      tags: flatpaks

    - include_tasks: tasks/optional_packages.yml
      tags: optional_packages

    - include_tasks: tasks/clone.yml
      tags: clone
