---
- name: Install several packages
  hosts: localhost
  become: yes
  tasks:

    - name: Update package manager repository
      dnf:
        update_cache: yes

    - name: Install git
      dnf:
        name: git
        state: present

    - name: Install fzf
      dnf:
        name: fzf
        state: present

    - name: Install neovim
      dnf:
        name:
          - neovim
          - python3-neovim
        state: present

    - name: Install gcc-c++
      dnf:
        name:
          - gcc-c++
        state: present

    - name: Install ripgrep
      dnf:
        name:
          - ripgrep
        state: present

    - name: Install go
      dnf:
        name: go
        state: present

    - name: Install htop
      dnf:
        name: go
        state: present

    - name: Install fzf
      dnf:
        name: fzf
        state: present

    - name: Install xclip
      dnf:
        name: xclip
        state: present
