---
- name: Clone install repo for gopl.io
  ansible.builtin.git:
    repo: 'https://github.com/adonovan/gopl.io/'
    dest: '~/Documents/gopl.io'
  tags: clone

- name: Clone install repo for coding interview university
  ansible.builtin.git:
    repo: 'https://github.com/jwasham/coding-interview-university'
    dest: '~/Documents/coding-interview-university'
  tags: clone

- name: Clone install repo for coding interview university
  ansible.builtin.git:
    repo: 'https://github.com/MichaelCade/90DaysOfDevOps'
    dest: '~/Documents/90DaysOfDevOps'
  tags: clone

- name: Clone install repo for coding interview university
  ansible.builtin.git:
    repo: 'https://github.com/bregman-arie/devops-exercises'
    dest: '~/Documents/devops-exercises'
  tags: clone

- name: Clone install repo for coding interview university
  ansible.builtin.git:
    repo: 'https://github.com/ThePrimeagen/.dotfiles'
    dest: '~/Documents/.dotfiles'
  tags: clone
