---
- name: Install Flatpak on Fedora
  become: true
  package:
    name: flatpak
    state: present
  tags: flatpaks

- name: Add Flathub remote repo
  become: true
  command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  tags: flatpaks

- name: Install Ansible Flatpak module
  shell: 'ansible-galaxy collection install community.general'
  tags: flatpaks

- name: Install Telegram
  community.general.flatpak:
    name: org.telegram.desktop
    state: present
  tags: flatpaks

- name: Install Discord
  community.general.flatpak:
    name: com.discordapp.Discord
    state: present
  tags: flatpaks

- name: Install qBitTorrent
  community.general.flatpak:
    name: org.qbittorrent.qBittorrent
    state: present
  tags: flatpaks

- name: Install OBS Studio
  community.general.flatpak:
    name: com.obsproject.Studio
    state: present
  tags: flatpaks

- name: Install Extension Manager
  community.general.flatpak:
    name: com.mattjakeman.ExtensionManager
    state: present
  tags: flatpaks

- name: Install VLC
  community.general.flatpak:
    name: org.videolan.VLC
    state: present
  tags: flatpaks

- name: Install Browser
  community.general.flatpak:
    name: com.brave.Browser
    state: present
  tags: flatpaks

- name: Install Stremio
  community.general.flatpak:
    name: com.stremio.Stremio
    state: present
  tags: flatpaks

# - name: Install Chrome
#   community.general.flatpak:
#     name: com.google.Chrome
#     state: present
#   tags: flatpaks

- name: Install GBA emulator
  community.general.flatpak:
    name: io.mgba.mGBA
    state: present
  tags: flatpaks

- name: Install Bitwarden
  community.general.flatpak:
    name: com.bitwarden.desktop
    state: present
  tags: flatpaks

