---
- name: Install kitty package
  package:
    name: kitty
    state: present
  tags:
    - kitty

- name: Deletes ~/.config/kitty directory
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.config/kitty"
    state: absent
  tags:
    - kitty
    - stow_kitty_conf

- name: Creates ~/.config/kitty directory
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.config/kitty"
    state: directory
  tags:
    - kitty
    - stow_kitty_conf

- name: Create symbolic link for kitty.conf
  file:
    src: "{{ lookup('env', 'HOME') }}/dotfiles/.config/kitty/kitty.conf"
    dest: "{{ lookup('env', 'HOME') }}/.config/kitty/kitty.conf"
    state: link
  tags:
    - kitty
    - stow_kitty_conf
