---
- name: Remove node version manager Volta
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.volta"
    state: absent
  tags: node

- name: Install node version manager Volta
  ansible.builtin.shell: curl https://get.volta.sh | bash -s -- --skip-setup
  tags: node

- name: Install node
  ansible.builtin.shell: "{{ lookup('env', 'HOME') }}/.volta/bin/volta install node"
  tags: node
