---
- name: Deletes lazy.vim config file
  ansible.builtin.file:
    path: '~/.config/nvim'
    state: absent
  tags: nvim

- name: Deletes lazy.vim share folder
  ansible.builtin.file:
    path: '~/.local/share/nvim/lazy'
    state: absent
  tags: nvim

- name: Deletes lazy.vim state folder
  ansible.builtin.file:
    path: '~/.local/state/nvim/lazy'
    state: absent
  tags: nvim

- name: Install neovim package for Ubuntu
  package:
    name: neovim
  tags: nvim
  when: ansible_pkg_mgr == 'apt'

- name: Install neovim package for Fedora
  package:
    name: 
      - neovim
      - python3-neovim
  tags: nvim
  when: ansible_pkg_mgr == 'dnf'

- name: Install kickstart neovim requirements
  package:
    name:
      - ripgrep
      - fd-find
  tags: nvim

- name: Install more kickstart neovim requirements for Ubuntu
  apt:
    name:
      - build-essential
  tags: nvim
  when: ansible_pkg_mgr == 'apt'

- name: Install more kickstart neovim requirements for Fedora
  dnf:
    name:
      - gcc
      - gcc-c++
  tags: nvim
  when: ansible_pkg_mgr == 'dnf'
      
- name: Clone install kickstart
  ansible.builtin.git:
    repo: 'https://github.com/nvim-lua/kickstart.nvim.git'
    dest: '~/.config/nvim'
  tags: nvim
  when: ansible_pkg_mgr == 'dnf'

- name: Remove after folder
  ansible.builtin.file:
    path: '~/.config/nvim/after'
    state: absent
  tags: nvim
  when: ansible_pkg_mgr == 'dnf'

- name: Remove folder plugins
  ansible.builtin.file:
    path: '~/.config/nvim/lua/custom/plugins'
    state: absent
  tags: nvim
  when: ansible_pkg_mgr == 'dnf'

- name: Symlink folder after
  become: yes
  file:
    src: '~/dotfiles/after'
    dest: '~/.config/nvim/after'
    state: link
  tags: nvim
  when: ansible_pkg_mgr == 'dnf'

- name: Symlink folder plugins
  become: yes
  file:
    src: '~/dotfiles/plugins'
    dest: '~/.config/nvim/lua/custom/plugins'
    state: link
  tags: nvim
  when: ansible_pkg_mgr == 'dnf'

- name: Change init.lua so that Neovim displays full file path
  shell: >
    sed -i '/component_separators/s/\(\s*\)\(component_separators\s*=\s*[^,]*,\)/\1\2\n\1path = 2,/' ~/.config/nvim/init.lua
  tags: nvim
  when: ansible_pkg_mgr == 'dnf'

- name: Enabling highlighted search for kickstart neovim
  shell: >
    sed -i 's/vim\.o\.hlsearch = false/vim.o.hlsearch = true/' ~/.config/nvim/init.lua
  tags: nvim
  when: ansible_pkg_mgr == 'dnf'

