---
- name: Install neovim package for Ubuntu
  package:
    name: neovim
  tags: nvim
  when: ansible_pkg_mgr == 'apt'

- name: Install neovim package for Fedora
  package:
    name: 
      - neovim
      - python3-neovim
  tags: nvim
  when: ansible_pkg_mgr == 'dnf'

- name: Install neovim requirements
  package:
    name:
      - ripgrep
      - fd-find
  tags: nvim

- name: Install more neovim requirements for Ubuntu
  apt:
    name:
      - build-essential
  tags: nvim
  when: ansible_pkg_mgr == 'apt'

- name: Install more neovim requirements for Fedora
  dnf:
    name:
      - gcc
      - gcc-c++
  tags: nvim
  when: ansible_pkg_mgr == 'dnf'
      
- name: Clone install kickstart
  ansible.builtin.git:
    repo: 'https://github.com/nvim-lua/kickstart.nvim.git'
    dest: '~/.config/nvim'
  tags: nvim
