---
- name: Deletes lazy.vim config file
  ansible.builtin.file:
    path: '~/.config/nvim'
    state: absent
  tags: nvim

- name: Deletes lazy.vim
  ansible.builtin.file:
    path: '~/.local/share/nvim/lazy'
    state: absent
  tags: nvim

- name: Deletes lazy.vim
  ansible.builtin.file:
    path: '~/.local/state/nvim/lazy'
    state: absent
  tags: nvim

- name: Deletes lazy.vim
  ansible.builtin.file:
    path: '~/.config/nvim/lazy-lock.json'
    state: absent
  tags: nvim

- name: Install neovim package for Ubuntu
  package:
    name: neovim
  tags: nvim
  when: ansible_pkg_mgr == 'apt'

- name: Install neovim package for Fedora
  package:
    name: 
      - neovim
      - python3-neovim
  tags: nvim
  when: ansible_pkg_mgr == 'dnf'

- name: Install kickstart neovim requirements
  package:
    name:
      - ripgrep
      - fd-find
  tags: nvim

- name: Install more kickstart neovim requirements for Ubuntu
  apt:
    name:
      - build-essential
  tags: nvim
  when: ansible_pkg_mgr == 'apt'

- name: Install more kickstart neovim requirements for Fedora
  dnf:
    name:
      - gcc
      - gcc-c++
  tags: nvim
  when: ansible_pkg_mgr == 'dnf'
      
- name: Clone install kickstart
  ansible.builtin.git:
    repo: 'https://github.com/nvim-lua/kickstart.nvim.git'
    dest: '~/.config/nvim'
  tags: nvim

- name: Change init.lua so that Neovim displays full file path
  shell: >
    sed -i '/component_separators/s/\(\s*\)\(component_separators\s*=\s*[^,]*,\)/\1\2\n\1path = 2,/' ~/.config/nvim/init.lua
  tags: nvim

