---
- name: Deletes lazy.vim config file
  ansible.builtin.file:
    path: '~/.config/nvim'
    state: absent
  tags: nvim

- name: Deletes lazy.vim share folder
  ansible.builtin.file:
    path: '~/.local/share/nvim/lazy'
    state: absent
  tags: nvim

- name: Deletes lazy.vim state folder
  ansible.builtin.file:
    path: '~/.local/state/nvim/lazy'
    state: absent
  tags: nvim

- name: Install neovim package for Ubuntu
  package:
    name: neovim
  tags: nvim
  when: ansible_pkg_mgr == 'apt'

- name: Install neovim package for Fedora
  package:
    name: 
      - neovim
      - python3-neovim
  tags: nvim
  when: ansible_pkg_mgr == 'dnf'

- name: Install neovim requirements
  package:
    name:
      - ripgrep
      - fd-find
  tags: nvim

- name: Install more neovim requirements for Ubuntu
  apt:
    name:
      - build-essential
  tags: nvim
  when: ansible_pkg_mgr == 'apt'

- name: Install more neovim requirements for Fedora
  dnf:
    name:
      - gcc
      - gcc-c++
  tags: nvim
  when: ansible_pkg_mgr == 'dnf'
      

- name: Remove after folder
  ansible.builtin.file:
    path: '~/.config/nvim/after'
    state: absent
  tags: nvim
  when: ansible_pkg_mgr == 'dnf'

- name: Remove folder plugins
  ansible.builtin.file:
    path: '~/.config/nvim/lua/custom/plugins'
    state: absent
  tags: nvim
  when: ansible_pkg_mgr == 'dnf'

- name: Symlink init.lua
  become: yes
  file:
    src: '~/dotfiles/init.lua'
    dest: '~/.config/nvim/init.lua'
    state: link
  tags: nvim
  when: ansible_pkg_mgr == 'dnf'

- name: Symlink folder after
  become: yes
  file:
    src: '~/dotfiles/after'
    dest: '~/.config/nvim/after'
    state: link
  tags: nvim
  when: ansible_pkg_mgr == 'dnf'

- name: Symlink folder plugins
  become: yes
  file:
    src: '~/dotfiles/lua'
    dest: '~/.config/nvim/lua'
    state: link
  tags: nvim
  when: ansible_pkg_mgr == 'dnf'

