---
- name: Install go for Ubuntu
  package:
    name: golang
    state: present
  tags: optional_packages
  when: ansible_pkg_mgr == 'apt'

- name: Install go for Fedora
  package:
    name: go
    state: present
  tags: optional_packages
  when: ansible_pkg_mgr == 'dnf'

- name: Install bat
  package:
    name: bat
    state: present
  tags: optional_packages

- name: Install htop
  package:
    name: htop
    state: present
  tags: optional_packages

- name: Install btop
  package:
    name: btop
    state: present
  tags: optional_packages

- name: Install tldr
  package:
    name: tldr
    state: present
  tags: optional_packages

- name: Install xkill for Fedora
  dnf:
    name: xkill
  tags: optional_packages
  when: ansible_pkg_mgr == 'dnf'
