---
- name: Install go for Ubuntu
  package:
    name: golang
    state: present
  when: ansible_pkg_mgr == 'apt'
  tags: optional_packages

- name: Install go for Fedora
  package:
    name: go
    state: present
  when: ansible_pkg_mgr == 'dnf'
  tags: optional_packages

- name: Install bat
  package:
    name: bat
    state: present
  tags: optional_packages

- name: Install htop
  package:
    name: htop
    state: present
  tags: optional_packages

- name: Install btop
  package:
    name: btop
    state: present
  tags: optional_packages

- name: Install tldr
  package:
    name: tldr
    state: present
  tags: optional_packages

- name: Install github cli
  package:
    name: gh
    state: present
  tags: optional_packages

- name: Install gnome-tweaks
  package:
    name: gnome-tweaks
    state: present
  tags: optional_packages

- name: Install xkill for Fedora
  dnf:
    name: xkill
  when: ansible_pkg_mgr == 'dnf'
  tags: optional_packages

- name: Install ffmpeg
  package:
    name: ffmpeg
    state: present
  tags: optional_packages

- name: Install yt-dlp
  package:
    name: yt-dlp
    state: present
  tags: optional_packages

- name: Install rsync
  package:
    name: rsync
    state: present
  tags: optional_packages

- name: Install rclone
  package:
    name: rclone
    state: present
  tags: optional_packages
