---
- name: Remove tmux-windowizer
  ansible.builtin.file:
    path: "/usr/local/bin/tmux-windowizer"
    state: absent
  tags: scripts

- name: Remove tmux-sessionizer
  ansible.builtin.file:
    path: "/usr/local/bin/tmux-sessionizer"
    state: absent
  tags: scripts

- name: Remove tmux-vimionizer
  ansible.builtin.file:
    path: "/usr/local/bin/tmux-vimionizer"
    state: absent
  tags: scripts

- name: Remove tmux-cht.sh
  ansible.builtin.file:
    path: "/usr/local/bin/tmux-cht.sh"
    state: absent
  tags: scripts

- name: Remove gclone script
  ansible.builtin.file:
    path: "/usr/local/bin/gclone"
    state: absent
  tags: scripts

- name: Create symlink to tmux-windowizer
  become: true
  file:
    src: "~/dotfiles/bin/tmux-windowizer"
    dest: "/usr/local/bin/tmux-windowizer"
    state: link
  tags: scripts

- name: Create symlink to tmux-sessionizer 
  become: true
  file:
    src: "~/dotfiles/bin/tmux-sessionizer"
    dest: "/usr/local/bin/tmux-sessionizer"
    state: link
  tags: scripts

- name: Create symlink to tmux-vimionizer 
  become: true
  file:
    src: "~/dotfiles/bin/tmux-vimionizer"
    dest: "/usr/local/bin/tmux-vimionizer"
    state: link
  tags: scripts

- name: Create symlink to tmux-cht.sh
  become: true
  file:
    src: "~/dotfiles/bin/tmux-cht.sh"
    dest: "/usr/local/bin/tmux-cht.sh"
    state: link
  tags: scripts

- name: Create symlink to gclone
  become: true
  file:
    src: "~/dotfiles/bin/gclone"
    dest: "/usr/local/bin/gclone"
    state: link
  tags: scripts

