---
- name: Install stow
  package:
    name: stow
    state: present
  tags:
    - stow
    - gitconfig
    - zshrc
    - tmux
    
- name: Remove gitconfig
  file:
    path: ~/.gitconfig
    state: absent
  tags:
    - stow
    - gitconfig

- name: Stow gitconfig
  shell: stow gitconfig
  tags:
    - stow
    - gitconfig

- name: Remove zshrc
  file:
    path: ~/.zshrc
    state: absent
  tags:
    - stow
    - zshrc

- name: Stow zshrc
  shell: stow zsh
  tags:
    - stow
    - zshrc

- name: Remove tmux.conf
  file:
    path: ~/.tmux.conf
    state: absent
  tags:
    - stow
    - tmux

- name: Remove tmux-cht-languages
  file:
    path: ~/.tmux-cht-languages
    state: absent
  tags:
    - stow
    - tmux

- name: Remove tmux-cht-command
  file:
    path: ~/.tmux-cht-command
    state: absent
  tags:
    - stow
    - tmux

- name: Stow tmux
  shell: stow tmux
  tags:
    - stow
    - tmux

- name: Apply changes to tmux configurations
  shell: tmux source-file ~/.tmux.conf
  tags:
    - stow
    - tmux

- name: Apply changes to zshrc configurations
  shell: source zshrc
  tags:
    - stow
    - zshrc

