---
- name: install zsh package
  apt:
    name: zsh
  tags: zsh
  when: ansible_pkg_mgr == 'apt'

- name: install zsh package
  dnf:
    name: zsh
  tags: zsh
  when: ansible_pkg_mgr == 'dnf'

- name: install chsh command
  apt:
    name: passwd
  tags: zsh
  when: ansible_pkg_mgr == 'apt'

- name: install which command
  dnf:
    name: which
  tags: zsh
  when: ansible_pkg_mgr == 'dnf'

# - name: Set default shell to zsh on Ubuntu
#   become: true
#   shell: chsh -s $(which zsh)
#   tags: zsh
#   when: ansible_pkg_mgr == 'apt'
#
# - name: Set default shell to zsh on Fedora
#   become: true
#   shell: chsh -s $(which zsh)
#   tags: zsh
#   when: ansible_pkg_mgr == 'dnf'
