
- name: Install git
  package:
    name: git
    state: present
  tags: zsh

- name: Install oh my zsh
  package:
    name: zsh
    state: present
  tags: zsh

- name: install chsh command
  dnf:
    name: util-linux-user
  tags: zsh
  when: ansible_pkg_mgr == 'dnf'

- name: install which command
  dnf:
    name: which
  tags: zsh

- name: Set default shell to zsh on Ubuntu
  become: true
  shell: chsh -s $(which zsh)
  tags: zsh
  when: ansible_pkg_mgr == 'apt'

# - name: Set default shell to zsh on Fedora
#   become: true
#   shell: chsh -s $(which zsh)
#   tags: zsh
#   when: ansible_pkg_mgr == 'dnf'

- name: Install oh my zsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  tags: zsh

- name: Install zsh-syntax-highlighting 
  shell: git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
  tags: zsh

- name: Add zsh-syntax-highlighting
  shell: sed -i 's/(git/(git zsh-syntax-highlighting/' ~/.zshrc
  tags: zsh

- name: Install zsh-autosuggestions plugin
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions'
    dest: '~/.oh-my-zsh/plugins/zsh-autosuggestions'
  tags: zsh

- name: Add zsh-autosuggestions on .zshrc plugin list
  shell: sed -i 's/(git/(git zsh-autosuggestions/' ~/.zshrc
  tags: zsh

