return {
	{ "nvim-neo-tree/neo-tree.nvim", enabled = false },
	{ "jesseduffield/lazygit", enabled = false },
	{ "rcarriga/nvim-notify", enabled = false },
	{ "echasnovski/mini.surround", enabled = false },
	{ "echasnovski/mini.ai", enabled = false },
	{ "echasnovski/mini.pairs", enabled = false },
	{ "folke/persistence.nvim", enabled = false },
	{ "folke/flash.nvim", enabled = false },
	{ "folke/noice.nvim", enabled = false },
	{ "folke/trouble.nvim", enabled = false },
	{ "RRethy/vim-illuminate", enabled = false },
	{ "ggandor/leap.nvim", enabled = false },
	{ "ggandor/flit.nvim", enabled = false },
	{ "akinsho/bufferline.nvim", enabled = false },
	{ "nvimdev/dashboard-nvim", enabled = false },
}
